# See https://github.com/krzema12/github-actions-typing
inputs:
  images:
    type: list
    separator: '\n'
    list-item:
      type: string
  tags:
    type: list
    separator: '\n'
    list-item:
      type: string
    required: false
  flavor:
    type: list
    separator: '\n'
    list-item:
      type: string
    required: false
  labels:
    type: list
    separator: '\n'
    list-item:
      type: string
    required: false
  sep-tags:
    type: string
    required: false
  sep-labels:
    type: string
    required: false
  bake-target:
    type: string
    required: false
